modLoader="javafml"
loaderVersion="[1,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Flemmli97/Flan/issues"
[[mixins]]
config = "flan.mixins.json"
[[mixins]]
config = "flan.forge.mixins.json"
[[mods]] 
modId="flan"
version="${version}"
displayName="Flan"
displayURL="${homepage}"
logoFile="icon.png"
authors="Flemmli97"
description='''Flan (Forge version): A serverside claiming mod'''
[[dependencies.flan]]
modId="minecraft"
type="required"
versionRange="[${mcversion},)"
ordering="NONE"
side="BOTH"
[[dependencies.flan]]
modId="neoforge"
type="required"
versionRange="[${forge_version},)"
ordering="NONE"
side="BOTH"
